## DAX
This section includes all of my DAX measures and tables used in the various figures within the Dashboard.
  - **Parts Used Table.dax:** This calculated table restructures the inventory data into a single unified parts table. It stacks blades, motors, and frames into one shared format with the product serial number, part type, part serial number, factory, and part cost. This made it easier to analyze factory-level performance across all component types using one consistent table instead of separate blade, motor, and frame tables. The LOOKUPVALUE functions pull the correct factory and unit cost from each component table, while UNION combines the three part categories into one dataset.

  - **Plant Defect Impact table.dax:** This calculated table isolates the parts that were actually responsible for a defect. It starts with the unified Parts Used table, adds return details such as defect status, defect part, refund amount, and return date, then filters the results to only include defective returns where the part type matches the reported defective part. This prevents refund impact from being assigned to every part in a returned product. Instead, only the factory that produced the defective component receives the return and refund impact.
  - **Part Defect Rate.dax:** This measure calculates the percentage of products associated with a selected part, factory, or part type that resulted in a defect. It counts the distinct defective returned products and divides that by the total distinct products in the current Parts Used filter context. TREATAS is used to apply the selected products from Parts Used to the Returns table, allowing defect rates to respond correctly to part-level visuals and slicers.
  - **Refund Amount Caused by Plant.dax:** This measure calculates the total refund amount directly attributed to the plant that produced the defective part. Because it uses the Plant Defect Impact table, the refund amount is only assigned to the factory responsible for the defective component, rather than every factory involved in the returned product.

  - **Defective Returns Caused by Plant.dax:** This measure counts the number of unique defective returned products attributed to each plant. Because it uses the Plant Defect Impact table, each return is only counted for the factory that produced the defective part, preventing the same return from being assigned to unrelated component plants.
  - **Plant Refund Impact.dax:** This measure shows the refund impact as a negative value, making it easier to represent refunds as a reduction to profit. It uses the Plant Defect Impact table, so the negative refund amount is only assigned to the plant responsible for producing the defective component.

  - **Factory with Highest Part Defect Rate.dax:** This measure identifies the factory with the highest part defect rate and displays both the factory name and its defect percentage. It first calculates the defect rate for each factory using the existing Part Defect Rate measure, then uses TOPN to select the highest-ranking factory. The final output is formatted as a dashboard-ready label showing the factory and its defect rate.


  - **Plant with Highest Defective Returns.dax:** This measure identifies the plant with the highest number of defective returns and displays the plant name with the return count. It captures the selected part type from the Parts Used slicer, applies that selection to the Plant Defect Impact table using TREATAS, and then ranks plants by defective return count. TOPN selects the highest-ranking plant, while the final output formats the result as a dashboard-ready label.

  - **Plant with Highest Refund Impact.dax:** This measure identifies the plant with the highest refund impact and displays both the plant name and total refund amount. It captures the selected part type from the Parts Used slicer, applies that filter to the Plant Defect Impact table with TREATAS, and ranks plants by refund amount. TOPN selects the plant with the highest refund total, and the final output formats the result as a dashboard-ready label.

  - **Factory Visible for Selected Part Type.dax:** This measure controls whether a factory should appear in visuals based on the selected part type. It captures the selected part type from the Parts Used slicer, checks which factories in Plant Defect Impact match that selection, and returns the number of matching rows. When used as a visual-level filter set to greater than 0, it hides factories that are not relevant to the selected part type. Used as a filter in Refund and Returns Caused by Plant and Returns and Refund Impact Caused by Plant charts.
